#!/usr/bin/env python3
"""
Publish this working copy to the student repository.

One job worth automating: `assignment.py` is the only file that has ever held
held-out data, and it is also the file students read. This strips the data on
the way out, so the answer sheet cannot reach a student checkout by someone
forgetting a step.

    python sync.py ../../../tmp/spikey-dsl-1
"""

import pathlib
import re
import shutil
import sys

HERE = pathlib.Path(__file__).resolve().parent

WEB = ["index.html", "app.js", "lang.js", "examples.js", "style.css"]
MODULES = ["__init__", "values", "core", "patterns", "types", "expr", "grammar",
           "syntax", "runtime", "project", "notation", "notation_mr",
           "notation_spark", "metrics", "contest", "shapes", "attest",
           "langserver"]

# Held-out literals, stripped from the student-facing copy.
STRIP = [
    re.compile(r"\n    holdout='(?:[^']|'(?!,\n))*',(?=\n)"),
    re.compile(r"\n    holdout_expects=\[(?:[^\]]|\][^,])*\],(?=\n)"),
]


# The banner every generated file carries, so it is obvious in an editor that
# this is not the place to change anything.
BANNER = "GENERATED by dsviz/sync.py — edit dsviz/, not this copy"


def stamp(text: str, name: str) -> str:
    """
    Put the banner in the file's own comment syntax.

    Each language gets the syntax it actually has. CSS has no `//` comment —
    a stray one there is a parse error, and the browser discards the rule set
    after it, which silently killed the stylesheet. HTML keeps its banner
    *after* the doctype, so nothing precedes it.
    """
    if name.endswith(".css"):
        return f"/* {BANNER} */\n" + text
    if name.endswith(".js"):
        return f"// {BANNER}\n" + text
    if name.endswith(".html"):
        # The doctype has to come first; put the banner on the line after it.
        doctype, sep, rest = text.partition("\n")
        return f"{doctype}{sep}<!-- {BANNER} -->\n{rest}"
    return f"# {BANNER}\n" + text


def unstamp(text: str) -> str:
    """The content without its banner, for comparing against the source."""
    lines = text.split("\n")
    # html carries the banner on the second line, after the doctype.
    for i in (0, 1):
        if i < len(lines) and BANNER in lines[i]:
            return "\n".join(lines[:i] + lines[i + 1:])
    return text


def write_generated(src: pathlib.Path, dest: pathlib.Path) -> None:
    dest.write_text(stamp(src.read_text(), dest.name))


def check_drift(app: pathlib.Path) -> list:
    """
    Which generated files no longer match their source.

    Returns (name, description) for anything edited in place. assignment.py is
    excluded: its copy is deliberately different, having had the answers
    stripped out of it.
    """
    out = []
    pairs = [(HERE / "web" / n, app / n) for n in WEB]
    pairs += [(HERE / "dsviz" / f"{n}.py", app / "dsviz" / f"{n}.py")
              for n in MODULES]
    for src, dest in pairs:
        if not dest.exists():
            continue
        current = dest.read_text()
        if unstamp(current) == src.read_text():
            continue
        # A missing banner means the file was written by something other than
        # this script — an edit in the wrong place. With the banner intact it
        # is the ordinary case: the source has moved on and this is stale.
        # html carries its banner on line 2, after the doctype — the same two
        # positions `unstamp` accepts. Checking only the first line reported
        # every html sync as a hand-edit.
        edited = not any(BANNER in line
                         for line in current.split("\n", 2)[:2])
        out.append((dest.relative_to(app.parent),
                    "EDITED HERE — this change would be lost" if edited
                    else "stale; the source has changed"))
    return out


def main(target: str) -> int:
    dest = pathlib.Path(target).resolve()
    app = dest / "app"
    if not app.exists():
        print(f"no app/ under {dest} — is that the student repo?")
        return 1

    # Refuse to overwrite an edit that was made in the wrong place.
    #
    # app/ is generated, but nothing stops someone editing it, and a silent
    # overwrite means the change simply disappears — a fix that was never
    # running, debugged for an hour. Compare before copying and say what would
    # be lost.
    drifted = check_drift(app)
    edited = [d for d in drifted if "EDITED" in d[1]]
    if edited and "--force" not in sys.argv:
        print("REFUSING: these files were edited in the generated copy:\n")
        for name, detail in edited:
            print(f"  {name}  {detail}")
        print("\napp/ is generated by this script. If the change belongs in "
              "the language,\nmake it in dsviz/ and sync again. If it was a "
              "mistake, re-run with --force\nto discard it.")
        return 1

    for name in WEB:
        write_generated(HERE / "web" / name, app / name)
    for name in MODULES:
        write_generated(HERE / "dsviz" / f"{name}.py",
                        app / "dsviz" / f"{name}.py")

    # assignment.py, with the held-out data removed.
    src = (HERE / "dsviz" / "assignment.py").read_text()
    for pattern in STRIP:
        src = pattern.sub("", src)
    (app / "dsviz" / "assignment.py").write_text(stamp(src, "assignment.py"))

    leaked = [p.name for p in (app / "dsviz").glob("*.py")
              if "holdout_expects=[" in p.read_text()
              or re.search(r"^    holdout='", p.read_text(), re.M)]
    if leaked:
        print(f"REFUSING: held-out data still present in {leaked}")
        return 1

    # Task sources are program files, not Python, so they are published
    # alongside the modules — the browser reads them the same way the grader
    # does. Without this the editor opens every task empty.
    tasks_out = app / "tasks"
    tasks_out.mkdir(parents=True, exist_ok=True)
    tasks = sorted(p for p in pathlib.Path("tasks").iterdir()
                   if p.is_file() and not p.name.startswith("."))
    for task in tasks:
        shutil.copy(task, tasks_out / task.name)

    # The server is part of the product, not part of the checkout it lands in:
    # it owns the workspace and it is the only thing that writes `solutions/`,
    # so it is published from here like everything else.
    devcontainer = dest / ".devcontainer"
    devcontainer.mkdir(parents=True, exist_ok=True)
    write_generated(HERE / "server" / "serve.py", devcontainer / "serve.py")
    write_generated(HERE / "server" / "serve.sh", devcontainer / "serve.sh")
    (devcontainer / "serve.sh").chmod(0o755)

    # A student checkout has no `src/`. Loose .ds files there were the shortcut
    # around the editor — copy one into `solutions/` and you have a submission
    # nobody ever ran. Work lives in the workspace the server keeps instead.
    loose = dest / "src"
    if loose.is_dir():
        shutil.rmtree(loose)
        print("removed src/ — a student checkout keeps its work in the workspace")

    # The documentation site, built by `mkdocs build`, is served by the same
    # server as the editor rather than one of its own — the application is one
    # thing on one port, and `/docs/` is part of it.
    built = pathlib.Path("site")
    docs_out = app / "docs"
    if built.is_dir():
        if docs_out.exists():
            shutil.rmtree(docs_out)
        shutil.copytree(built, docs_out)

    print(f"synced {len(tasks)} task file(s),  {len(WEB)} page file(s) and {len(MODULES) + 1} module(s) "
          f"to {dest}")
    print("held-out data stripped — nothing in app/ reveals the answers")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1] if len(sys.argv) > 1 else "../spikey-dsl-1"))
